# Generated by Django 3.0.3 on 2020-05-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('car_model', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('transmission', models.SmallIntegerField(choices=[(1, 'Механическая'), (2, 'Автомат'), (3, 'Робот')], verbose_name='Коробка передач')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
            ],
        ),
    ]
